apiVersion: apps/v1
kind: Deployment
metadata:
  name: virtualrouter-controller
  namespace: virtualrouter
  labels:
    app: virtualrouter-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: virtualrouter-controller
  template:
    metadata:
      namespace: virtualrouter
      labels:
        app: virtualrouter-controller
    spec:
      serviceAccount: virtualrouter-controller-sa
      containers:
      - name: controller
        image: tmaxcloudck/virtualrouter-controller:vx.y.z
        imagePullPolicy: Always
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace