apiVersion: tmax.hypercloud.com/v1
kind: VirtualRouter
metadata:
  name: virtualrouter1
  namespace: virtualrouter
spec:
  deploymentName: example-virtualrouter
  replicas: 1
  vlanNumber: 210
  internalIP: 10.10.10.11
  internalNetmask: 255.255.255.0
  externalIP: 192.168.8.153
  externalNetmask: 255.255.255.0
  gatewayIP: 192.168.8.2
  image: 10.0.0.4:5000/virtualrouter:v0.2.0
  nodeSelector:
  - key: app
    value: test
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: requiredkey
            values: 
            - nfv
            operator: In
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: nfvnode
            values:
            - master
            operator: In
      - weight: 10
        preference:
          matchExpressions:
          - key: nfvnode
            values:
            - slave
            operator: In

