apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: virtualrouter-daemon
  namespace: virtualrouter
  labels:
    app: virtualrouter-daemon
spec:
  selector:
    matchLabels:
      app: virtualrouter-daemon
  template:
    metadata:
      labels:
        app: virtualrouter-daemon
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: virtualrouter/daemon
                    operator: In
                    values:
                      - deploy
      serviceAccount: virtualrouter-controller-sa
      hostNetwork: true
      hostPID: true
      containers:
      - name: networkdaemon
        image: tmaxcloudck/virtualrouter-daemon:vx.y.z
        imagePullPolicy: Always
        env:
        - name: nodeName
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          capabilities:
            add:
            # - '*'
            - NET_RAW
            - NET_ADMIN
          privileged: true
        volumeMounts:
        - name: criosock
          mountPath: /var/run/crio/crio.sock
      volumes:
      - name: criosock
        hostPath:
          path: /var/run/crio/crio.sock 
