apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: networkdaemon
  namespace: virtualrouter
  labels:
    app: daemon
spec:
  selector:
    matchLabels:
      name: networkdaemon
  template:
    metadata:
      labels:
        name: networkdaemon
    spec:
      serviceAccount: virtualrouter-controller-sa
      hostNetwork: true
      hostPID: true
      containers:
      - name: networkdaemon
        image: tmaxcloud.io/virtualrouter-daemon:v0.1.3-dev
        imagePullPolicy: Always
        env:
        - name: nodeName
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          capabilities:
            add:
            # - '*'
            - NET_RAW
            - NET_ADMIN
          privileged: true
        volumeMounts:
        - name: criosock
          mountPath: /var/run/crio/crio.sock
      volumes:
      - name: criosock
        hostPath:
          path: /var/run/crio/crio.sock 